### ISSUE TITLE
重做项目官网

### ISSUE THREAD

**Issue by shaunthegeek** [stonecutter/library-in#1]
目前这个项目里包括：

- 官网 https://buzhanzuo.com/
- 后端接口 https://buzhanzuo.com/api
- 管理后台 https://buzhanzuo.com/admin
- 后端输出的简单页面 https://bzz.mobi/s/1000265822

官网很烂，需要重做，和产品确认一下：没有设计稿的话，技术就去网上挑几个技术好的模板，让产品确认其中一个。

**Comment by shaunthegeek** [comment]
我们目前已经有了 组织级别的pages，https://github.com/stonecutter/stonecutter.github.io
现在需要做项目级的pages，按照github文档，最终发布可以使用 master 或 gh-pages 分支，所以我们用master做开发，通过CI自动构建，把结果push到gh-pages，即可。

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

如果域名指向github，动态页面就不能用了，比如/admin 和 /api，所以域名先不指向。做完通过stonecutter.github.io/project 看看效果。

**Comment by shaunthegeek** [comment]
CI已经买了这个：https://github.com/marketplace/circleci
文档：https://circleci.com/docs/

**Comment by shaunthegeek** [comment]
参考做公司官网的文档：https://github.com/stonecutter/stonecutter.github.io/issues/1

如果目前的UI没问题的话，继续用也行。要么挑个模板，收费的我来买。

**Comment by shaunthegeek** [comment]
circleci.com 配置：
![image](https://user-images.githubusercontent.com/4971414/56031050-f45ccc80-5d50-11e9-8c4e-26bf073d86da.png)

```
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
```
